# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0a066aa4a9af33620d0306363d6be337587ac927fda18c91f2e07a6e5587ddb3f50ff27decc0e0b3c44adf505587e68312e9ff2b87a0940463a7e4f62d3e812

test:
  secret_key_base: 42b1f8fab35cac087abeaee1c6e91d80bcf4f0821f419d5b3a18de5a8fdeed968ddaa9bc23744073cd4cbe93dc2a4d9fcd451110f7c56865dafdf173afa54047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
